[package]
name = "dedupe_desktop_tauri"
version = "1.2.0"
edition = "2021"

[package.metadata]

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2" }
tauri-plugin-dialog = "2"
dedupe_backend = { path = "../../../crates/backend" }

[workspace]
