pub mod cancel;
pub mod config;
pub mod dedupe_ram;
pub mod disk;
pub mod disk_sort;
pub mod engine;
pub mod epub_reader;
pub mod frequency;
pub mod fuzzy;
pub mod ngram;
pub mod pdf_reader;
pub mod progress;
pub mod set_ops;
pub mod stats;
pub mod text_line_reader;
pub mod token_iter;
pub mod word_checker;
pub mod writer;

pub use cancel::{is_canceled_error, CancelCheck, Canceled, CancellationToken, NoCancel};
pub use config::{Config, ConfigError, DiskAlphabeticalMode, Mode, OutputOrdering};
pub use engine::{effective_mode, run, run_with_control};
pub use frequency::token_frequency;
pub use fuzzy::{fuzzy_cluster, fuzzy_dedup_inputs, FuzzyStats};
pub use ngram::{ngram_extract, NgramStats};
pub use progress::{NoProgress, ProgressEvent, ProgressSink};
pub use set_ops::{set_op, SetOp};
pub use stats::{FileStats, Stats};
pub use word_checker::WordChecker;
