pub mod cancel;
pub mod config;
pub mod dedupe_ram;
pub mod disk;
pub mod disk_sort;
pub mod engine;
pub mod pdf_reader;
pub mod progress;
pub mod word_checker;
pub mod stats;
pub mod text_line_reader;
pub mod token_iter;
pub mod writer;

pub use cancel::{is_canceled_error, CancelCheck, Canceled, CancellationToken, NoCancel};
pub use config::{Config, DiskAlphabeticalMode, Mode, OutputOrdering};
pub use engine::{run, run_with_control};
pub use progress::{NoProgress, ProgressEvent, ProgressSink};
pub use stats::Stats;
pub use word_checker::WordChecker;
